---
title: "neuralNetworkPractice"
author: "Rita Hippe"
date: "2024-01-31"
output: html_document
---

```{r}
# run in console:
#install.packages(c('neuralnet','keras','tensorflow'),dependencies = T)


library(tidyverse)
library(MASS) # data
library(neuralnet) 
library(ggplot2)



```

# Get data
```{r}
data <- Boston

#apply(data,2,function(x) sum(is.na(x))) # run to make sure no missing data


set.seed(500)


index <- sample(1:nrow(data),round(0.75*nrow(data)))
train <- data[index,]
test <- data[-index,]
lm.fit <- glm(medv~., data=train) # fitting reg linear regression model
#summary(lm.fit)
pr.lm <- predict(lm.fit,test)
MSE.lm <- sum((pr.lm - test$medv)^2)/nrow(test) # MSE is mean squared error

```

# Train neural network
```{r}

# Randomly selecting rows to assign to be part of training or testing data

maxs <- apply(data, 2, max) 
mins <- apply(data, 2, min)
scaled <- as.data.frame(scale(data, center = mins, scale = maxs - mins)) # normalizing data!!!
train_ <- scaled[index,]
test_ <- scaled[-index,]


n <- names(train_)
f <- as.formula(paste("medv ~", paste(n[!n %in% "medv"], collapse = " + ")))
nn <- neuralnet(f,data=train_,hidden=c(5,3),linear.output=T)

plot(nn)
```

# Test neural network
```{r}
pr.nn <- compute(nn,test_[,1:13])
pr.nn_ <- pr.nn$net.result*(max(data$medv)-min(data$medv))+min(data$medv)
test.r <- (test_$medv)*(max(data$medv)-min(data$medv))+min(data$medv)
MSE.nn <- sum((test.r - pr.nn_)^2)/nrow(test_)



print(paste0("Linear regression MSE: ",MSE.lm," and neural network MSE: ",MSE.nn))


```

# Comparing Predictions of NN and lm
```{r}

par(mfrow=c(1,2))
plot(test$medv,pr.nn_,col='red',main='Real vs predicted NN',pch=18,cex=0.7)
abline(0,1,lwd=2)
legend('bottomright',legend='NN',pch=18,col='red', bty='n')
plot(test$medv,pr.lm,col='blue',main='Real vs predicted lm',pch=18, cex=0.7)
abline(0,1,lwd=2)
legend('bottomright',legend='LM',pch=18,col='blue', bty='n', cex=.95)

plot(test$medv,pr.nn_,col='red',main='Real vs predicted NN',pch=18,cex=0.7)
points(test$medv,pr.lm,col='blue',pch=18,cex=0.7)
abline(0,1,lwd=2)
legend('bottomright',legend=c('NN','LM'),pch=18,col=c('red','blue'))
```


Resources
```{r}
# https://datascienceplus.com/fitting-neural-network-in-r/


```